#!/bin/sh
#
# This script tries to find the proper flags for the "aclocal" script:
# aclocal must be able to find elastiC's and gtk's aclocal macros.
#
# By default aclocal will search only in the same tree where it was
# installed ("/usr/local/share/aclocal" if installed in "/usr/local/bin", ...).
#
# If the "share/local" subdirectory residing in the subtree returned
# by "elastic-config --prefix" is *different* from the one reported
# by "aclocal --print-ac-dir", we return the proper -I flag.
# (We must be careful to not return the same directory multiple times).
#
# $Id$
#

# NOTE: on my personal installation, I've new auto* stuff in /usr/local
#       and system gtk is installed in /usr, so gtk aclocal macros are
#       in /usr/share/aclocal: we can't use both /usr/share/aclocal and
#       /usr/local/share/aclocal, because there are two different versions
#       of aclocal there (this makes impossible to use macros like
#       AM_PATH_GTK in configure.in)

aclocal_dir=`aclocal --print-ac-dir`

elastic_prefix=`elastic-config --prefix`
#gtk_prefix=`gtk-config --prefix`

if [ -z "$elastic_prefix" ];
then
    elastic_aclocal_dir=""
else
    elastic_aclocal_dir="${elastic_prefix}/share/aclocal"
fi

#if [ -z "$gtk_prefix" ];
#then
#    gtk_aclocal_dir=""
#else
#    gtk_aclocal_dir="${gtk_prefix}/share/aclocal"
#fi

output_aclocal_dir=""

if [ ! -z "$aclocal_dir" -a ! -z "$elastic_aclocal_dir" \
    -a "$aclocal_dir" != "$elastic_aclocal_dir" ];
then
    output_aclocal_dir="$elastic_aclocal_dir"
fi

#if [ ! -z "$aclocal_dir" -a ! -z "$gtk_aclocal_dir" \
#    -a "$aclocal_dir" != "$gtk_aclocal_dir" \
#    -a "$gtk_aclocal_dir" != "$output_aclocal_dir" ];
#then
#    output_aclocal_dir="$output_aclocal_dir $gtk_aclocal_dir"
#fi

output=""
for i in $output_aclocal_dir; do
    output="$output -I $i";
done
echo $output
exit 0
