#!/bin/bash
#
# A simple script to ease DLL compilation on mingw32
# cross compilation environment.
#
# Copyright (C) 2000 Marco Pantaleoni.
#

function emit_dllinit()
{
    cat >dllinit.c <<EOF
/* dllinit.c -- Portable DLL initialization. 
   Copyright (C) 1998, 1999 Free Software Foundation, Inc.
   Contributed by Mumit Khan (khan@xraylith.wisc.edu).

   I've used DllMain as the DLL "main" since that's the most common 
   usage. MSVC and Mingw32 both default to DllMain as the standard
   callback from the linker entry point. Cygwin, as of b20.1, also
   uses DllMain as the default callback from the entry point.

   The real entry point is typically always defined by the runtime 
   library, and usually never overridden by (casual) user. What you can 
   override however is the callback routine that the entry point calls, 
   and this file provides such a callback function, DllMain.

   Mingw32: The default entry point for mingw32 is DllMainCRTStartup
   which is defined in libmingw32.a This in turn calls DllMain which is
   defined here. If not defined, there is a stub in libmingw32.a which
   does nothing.

   Cygwin: The default entry point for Cygwin b20.1 or newer is
   __cygwin_dll_entry which is defined in libcygwin.a. This in turn
   calls the routine DllMain. If not defined, there is a stub in
   libcygwin.a which does nothing. 

   MSVC: MSVC runtime calls DllMain, just like Mingw32.

   Summary: If you need to do anything special in DllMain, just add it
   here. Otherwise, the default setup should be just fine for 99%+ of
   the time. I strongly suggest that you *not* change the entry point,
   but rather change DllMain as appropriate.

 */


#define WIN32_LEAN_AND_MEAN
#include <windows.h>
#undef WIN32_LEAN_AND_MEAN
#include <stdio.h>

BOOL APIENTRY DllMain (HINSTANCE hInst, DWORD reason, 
                       LPVOID reserved /* Not used. */ );

/*
 *----------------------------------------------------------------------
 *
 * DllMain --
 *
 *	This routine is called by the Mingw32, Cygwin32 or VC++ C run 
 *	time library init code, or the Borland DllEntryPoint routine. It 
 *	is responsible for initializing various dynamically loaded 
 *	libraries.
 *
 * Results:
 *      TRUE on sucess, FALSE on failure.
 *
 * Side effects:
 *
 *----------------------------------------------------------------------
 */
BOOL APIENTRY
DllMain (
	 HINSTANCE hInst /* Library instance handle. */ ,
	 DWORD reason /* Reason this function is being called. */ ,
	 LPVOID reserved /* Not used. */ )
{

  switch (reason)
    {
    case DLL_PROCESS_ATTACH:
      break;

    case DLL_PROCESS_DETACH:
      break;

    case DLL_THREAD_ATTACH:
      break;

    case DLL_THREAD_DETACH:
      break;
    }
  return TRUE;
}
EOF
}

# ========================================================================
#
# M A I N
#
# ========================================================================

mingw_prefix=i386-mingw32msvc-

DLLTOOL=${mingw_prefix}dlltool
DLLWRAP=${mingw_prefix}dllwrap
AS=${mingw_prefix}as
LD=${mingw_prefix}ld
GCC=${mingw_prefix}gcc

dllname=$1; shift
def=$1; shift;
linkwith=$1; shift
objects="$*"

INPUT_DEF_SWITCH=""
[ -n "$def" -a "x$def" != "x" ] && INPUT_DEF_SWITCH="--def $def"

LINKWITH_SWITCH=""
[ -n "$linkwith" -a "x$linkwith" != "x" ] && LINKWITH_SWITCH="$linkwith"

objs=""
for F in $objects; do
    case $F in
	*.[ao])	objs="$objs $F";;
    esac
done

basename=`basename $dllname .dll`
DLL_NAME=${basename}.dll
DLL_EXP_LIB=lib${basename}.a
if [ -n "$def" -a "x$def" != "x" ] ; then
    DLL_EXP_DEF=""
    OUTPUT_DEF_SWITCH=""
else
    DLL_EXP_DEF=${basename}.def
    OUTPUT_DEF_SWITCH="--output-def ${DLL_EXP_DEF}"
fi

DLL_OBJS="$objs dllinit.o"
DLL_LDFLAGS=""
DLL_LDLIBS="${LINKWITH_SWITCH}"

DLLTOOL_FLAGS=""
DLLWRAP_FLAGS="--as ${AS} --dlltool-name ${DLLTOOL} --export-all-symbols ${INPUT_DEF_SWITCH} ${OUTPUT_DEF_SWITCH} --implib ${DLL_EXP_LIB} --driver-name ${GCC}"

# Compile dllinit.c
emit_dllinit

echo "${GCC} ${CFLAGS} -c dllinit.c -o dllinit.o"
${GCC} ${CFLAGS} -c dllinit.c -o dllinit.o

# Link DLL
echo "$DLLWRAP $DLLWRAP_FLAGS -o $DLL_NAME $DLL_OBJS $DLL_LDFLAGS $DLL_LDLIBS"
$DLLWRAP $DLLWRAP_FLAGS -o $DLL_NAME $DLL_OBJS $DLL_LDFLAGS $DLL_LDLIBS

# Finally, also build import libraries for the Microsoft linker. You
# will either need to have some decent version of MSVC, or get lib.exe
# (and link.exe) from the (freely downloadable) Microsoft Platform SDK.

if type -p lib.exe && [ -n "$def" -a "$def" != '-' ]; then
    lib -name:${DLL_NAME} -def:${DLL_EXP_LIB} -out:${basename}.lib
fi

rm dllinit.c dllinit.o 2>/dev/null
